# Generated by Django 5.1.7 on 2025-09-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oqituvchilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250)),
                ('familiya', models.CharField(max_length=250)),
                ('sharifi', models.CharField(max_length=250)),
                ('tugulgan_sana', models.DateField()),
            ],
        ),
    ]
