# Generated by Django 5.1.7 on 2025-09-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_oqituvchilar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kafedralar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=250)),
                ('mudir', models.CharField(max_length=250)),
            ],
        ),
    ]
