# Generated by Django 5.1.7 on 2025-09-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_kafedralar'),
    ]

    operations = [
        migrations.AddField(
            model_name='oqituvchilar',
            name='Kafedra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kafedralar'),
        ),
    ]
