# Generated by Django 5.1.7 on 2025-09-24 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_oqituvchilar_kafedra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foydalanuvchi_rol', models.CharField(choices=[('prorektor', 'prorektor'), ('dekan', 'dekan'), ('kafedra mudiri', 'kafedra mudiri'), ('oqituvchi', 'oqituvchi')], max_length=50)),
                ('ism', models.CharField(max_length=250)),
                ('familiya', models.CharField(max_length=250)),
                ('sharifi', models.CharField(max_length=250)),
                ('tugulgan_sana', models.DateField()),
                ('Kafedra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kafedralar')),
            ],
        ),
        migrations.DeleteModel(
            name='Oqituvchilar',
        ),
    ]
