# Generated by Django 5.1.7 on 2025-09-24 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_foydalanuvchilar_delete_oqituvchilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafedralar',
            name='mudir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kafedra_mudiri', to='app.foydalanuvchilar'),
        ),
    ]
