# Generated by Django 5.1.7 on 2025-09-28 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_kafedralar_mudir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafedralar',
            name='mudir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kafedra_mudiri', to='app.foydalanuvchilar'),
        ),
    ]
