# Generated by Django 5.1.7 on 2025-09-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_kafedralar_mudir'),
    ]

    operations = [
        migrations.CreateModel(
            name='oquv_ishlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=250)),
                ('nomi', models.CharField(max_length=250)),
                ('sana', models.DateField()),
                ('fayl', models.FileField(upload_to='oquv_ishlari/')),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foydalanuvchilar')),
            ],
        ),
    ]
