# Generated by Django 5.1.7 on 2025-09-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_oquv_ishlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='oquv_ishlari',
            name='kategoriya',
            field=models.CharField(choices=[('Xalqaro', 'Xalqaro'), ('Respublika', 'Respublika')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='oquv_ishlari',
            name='turi',
            field=models.CharField(choices=[('Scopus', 'Scopus'), ('Maqola', 'Maqola'), ('Tezis', 'Tezis'), ('EHM guvohnomalar', 'EHM guvohnomalar'), ('patent', 'patent')], max_length=250),
        ),
    ]
