# Generated by Django 5.1.7 on 2025-09-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_oquv_ishlari_kategoriya_alter_oquv_ishlari_turi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='oquv_ishlari',
            new_name='oquvIshlari',
        ),
    ]
