# Generated by Django 5.1.7 on 2025-10-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_oquv_ishlari_oquvishlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='ilmiy_ishlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('Scopus', 'Scopus'), ('Maqola', 'Maqola'), ('Tezis', 'Tezis'), ('EHM guvohnomalar', 'EHM guvohnomalar'), ('patent', 'patent')], max_length=250)),
                ('nomi', models.CharField(max_length=250)),
                ('sana', models.DateField()),
                ('fayl', models.FileField(upload_to='oquv_ishlari/')),
                ('kategoriya', models.CharField(choices=[('Xalqaro', 'Xalqaro'), ('Respublika', 'Respublika')], max_length=250, null=True)),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foydalanuvchilar')),
            ],
        ),
    ]
