# Generated by Django 5.1.7 on 2025-10-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ilmiy_ishlari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oquvishlari',
            name='kategoriya',
        ),
        migrations.AddField(
            model_name='oquvishlari',
            name='betlar_soni',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ilmiy_ishlari',
            name='fayl',
            field=models.FileField(upload_to='ilmiy_ishlari/'),
        ),
        migrations.AlterField(
            model_name='oquvishlari',
            name='turi',
            field=models.CharField(choices=[('Uslubiy ko`rsatma', 'Uslubiy ko`rsatma'), ('O`quv qo`llanma', 'O`quv qo`llanma'), ('Darslik', 'Darslik'), ('Monografiya', 'Monografiya')], max_length=250),
        ),
    ]
