# Generated by Django 5.1.7 on 2025-10-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_oquvishlari_kategoriya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiy_ishlari',
            name='i_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
