# Generated by Django 5.1.7 on 2025-10-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_ilmiy_ishlari_i_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilmiy_ishlari',
            name='i_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
