# Generated by Django 5.1.7 on 2025-10-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_ilmiy_ishlari_i_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='oquvishlari',
            name='i_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
