# Generated by Django 5.1.7 on 2025-10-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_oquvishlari_i_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oquvishlari',
            old_name='i_id',
            new_name='o_id',
        ),
    ]
