# Generated by Django 5.1.7 on 2025-10-31 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_i_id_oquvishlari_o_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dekanatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=250)),
                ('dekan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dekan', to='app.foydalanuvchilar')),
            ],
        ),
    ]
