# Generated by Django 5.1.7 on 2025-10-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_dekanatlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dekanatlar',
            name='kafedralar',
            field=models.ManyToManyField(blank=True, related_name='dekanat_kafedralari', to='app.kafedralar'),
        ),
        migrations.AddField(
            model_name='kafedralar',
            name='oqituvchilar',
            field=models.ManyToManyField(blank=True, related_name='kafedra_oqituvchilari', to='app.foydalanuvchilar'),
        ),
    ]
