# Generated by Django 5.1.7 on 2025-10-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_dekanatlar_kafedralar_kafedralar_oqituvchilar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foydalanuvchilar',
            name='Kafedra',
        ),
        migrations.AddField(
            model_name='foydalanuvchilar',
            name='kafedra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foydalanuvchilari', to='app.kafedralar'),
        ),
    ]
