# Generated by Django 5.1.7 on 2025-10-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_foydalanuvchilar_kafedra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchilar',
            name='foydalanuvchi_rol',
            field=models.CharField(choices=[('prorektor', 'Prorektor'), ('dekan', 'Dekan'), ('kafedra mudiri', 'Kafedra mudiri'), ('oqituvchi', 'Oqituvchi')], max_length=50),
        ),
    ]
