# Generated by Django 5.1.7 on 2025-11-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_foydalanuvchilar_foydalanuvchi_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchilar',
            name='login_f',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foydalanuvchilar',
            name='parol',
            field=models.CharField(default=3, max_length=250),
            preserve_default=False,
        ),
    ]
