# Generated by Django 5.1.7 on 2025-11-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_foydalanuvchilar_login_f_foydalanuvchilar_parol'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchilar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foydalanuvchilar/'),
        ),
    ]
