# Generated by Django 5.2.8 on 2025-11-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_foydalanuvchilar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedralar',
            name='fakultet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultet', to='app.dekanatlar'),
        ),
    ]
