# Generated by Django 5.1.7 on 2025-11-23 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_kafedralar_fakultet'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchilar',
            name='fakulteti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fakulteti', to='app.dekanatlar'),
        ),
    ]
