# Generated by Django 5.2.8 on 2025-11-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_foydalanuvchilar_fakulteti'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiy_ishlari',
            name='ish_mualliflari',
            field=models.TextField(null=True),
        ),
    ]
