# Generated by Django 5.2.8 on 2025-11-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_ilmiy_ishlari_ish_mualliflari'),
    ]

    operations = [
        migrations.AddField(
            model_name='oquvishlari',
            name='ish_mualliflari',
            field=models.TextField(null=True),
        ),
    ]
