# Generated by Django 5.2.9 on 2025-12-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_oquvishlari_ish_mualliflari'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiy_ishlari',
            name='haqida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
